name: rent_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  logger: ^2.0.2+1
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.9
  cached_network_image: ^3.3.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.6
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0



flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FE724C"
  image: assets/logo/out_door.png

  android_12:
    color: "#FE724C"
    image: assets/logo/out_door.png

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/Fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/Fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/Fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/Fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/Fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/Fonts/SF-Pro-Display-Light.otf
          weight: 300